services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      # AI Services
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - GOOGLE_STT_API_KEY=${GOOGLE_STT_API_KEY:-}
      - GOOGLE_TTS_API_KEY=${GOOGLE_TTS_API_KEY:-}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - SARVAM_API_KEY=${SARVAM_API_KEY:-}
      # Piopiy Configuration
      - APP_ID=${APP_ID:-}
      - APP_SECRET=${APP_SECRET:-}
      - CALLER_ID=${CALLER_ID:-}
      - TO_NUMBER=${TO_NUMBER:-}
      - AGENT_NUMBER=${AGENT_NUMBER:-}
      - PIOPIY_NUMBER=${PIOPIY_NUMBER:-}
      # WebSocket and URLs
      - WEBSOCKET_URL=${WEBSOCKET_URL:-}
      - TTS_URL=${TTS_URL:-}
      # Deepgram
      - DG_API_KEY=${DG_API_KEY:-}
      # Database
      - MONGO_URI=${MONGO_URI:-mongodb://mongodb:27017/ai_agent}
      - MONGO_DB=${MONGO_DB:-ai_agent_assist}
      # Frontend Origins
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN:-}
      - FRONTEND_ORIGIN_ALT=${FRONTEND_ORIGIN_ALT:-http://localhost:3000}
    volumes:
      - .:/app
      - ./data:/app/data
    restart: unless-stopped

  backend-with-local-db:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      # AI Services
      - GROQ_API_KEY=${GROQ_API_KEY:-}
      - GOOGLE_STT_API_KEY=${GOOGLE_STT_API_KEY:-}
      - GOOGLE_TTS_API_KEY=${GOOGLE_TTS_API_KEY:-}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - SARVAM_API_KEY=${SARVAM_API_KEY:-}
      # Piopiy Configuration
      - APP_ID=${APP_ID:-}
      - APP_SECRET=${APP_SECRET:-}
      - CALLER_ID=${CALLER_ID:-}
      - TO_NUMBER=${TO_NUMBER:-}
      - AGENT_NUMBER=${AGENT_NUMBER:-}
      - PIOPIY_NUMBER=${PIOPIY_NUMBER:-}
      # WebSocket and URLs
      - WEBSOCKET_URL=${WEBSOCKET_URL:-}
      - TTS_URL=${TTS_URL:-}
      # Deepgram
      - DG_API_KEY=${DG_API_KEY:-}
      # Database
      - MONGO_URI=${MONGO_URI:-mongodb://mongodb:27017/ai_agent}
      - MONGO_DB=${MONGO_DB:-ai_agent_assist}
      # Frontend Origins
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN:-}
      - FRONTEND_ORIGIN_ALT=${FRONTEND_ORIGIN_ALT:-http://localhost:3000}
    volumes:
      - .:/app
      - ./data:/app/data
    restart: unless-stopped
    depends_on:
      - mongodb
    profiles:
      - local-db

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=ai_agent_assist
    volumes:
      - mongodb_data:/data/db
      - ./data:/data/backup
    restart: unless-stopped
    profiles:
      - local-db

volumes:
  mongodb_data:
